image:
  file: .gitpod.dockerfile
tasks:
  - init: lein deps
    command: mkdir .shadow-cljs
    command: echo 5555 > .shadow-cljs/socket-repl.port
    command: lein repl

vscode:
  extensions:
    - mauricioszabo.clover@0.0.4:MHmP3EBKs6lGCDNEAeixVg==