language: clojure

jdk:
  - openjdk:11.0.5

script:
  - lein test
  - npx shadow-cljs compile tests
  - node out/all-tests.js

before_install:
 - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | gpg --import; fi
 - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust; fi

deploy:
 - provider: script
   skip_cleanup: true
   script: scripts/deploy.sh
   on:
     tags: true

 - provider: script
   skip_cleanup: true
   script: scripts/deploy.sh
   on:
     branch: master

notifications:
  email: false
